# Use root/example as user/password credentials
version: '3.1'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "ParrotDev123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: unless-stopped
      
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db

  order-service:
    build: order-service/.
    ports:
      - "8080:80" 
    environment:
      - "ConnectionStrings__DefaultConnection=Server=sql-server-db;Database=backendDb;User=sa;Password=ParrotDev123;MultipleActiveResultSets=true"
    restart: on-failure
    depends_on:
      - sql-server-db

  user-service:
    build: user-service/.
    environment:
      DB_URI: mongodb://mongo:27017/parrot-users
      TOKEN_SECRET: 8at!7TtrV+J9@2ZHjrtqtyg9Tm_wN3^P3A?s9QWQ6y#ASpN!+Z8F!2U+s_nXs2
      EXPIRES_IN: 3600
    ports:
      - "3000:3000"
    links:
      - mongo

volumes:
  data01:
    driver: local
  mongodb_data_volume:
    external: true
  