# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db

  order-service:
    build: order-service/.
    ports:
      - "8080:80" 

  user-service:
    build: user-service/.
    environment:
      DB_URI: mongodb://mongo:27017/parrot-users
      TOKEN_SECRET: TOKEN_SECRET
      EXPIRES_IN: 3600
    ports:
      - "3000:3000"
    links:
      - mongo
volumes:
  mongodb_data_volume:
    external: true